build:
  environment:
        php:
            version: 7.0.20
  dependencies:
          before:
              - sudo composer self-update && composer --version
              - composer global require fxp/composer-asset-plugin:^1.3.1
              - composer install --prefer-source
              - composer global require "fxp/composer-asset-plugin:~1.0"
  tests:
    override:
      - command: 'php vendor/bin/codecept run --coverage --coverage-xml'
      - coverage:
          file: 'tests/data/_output/covegare.xml'
          format: clover
imports:
    - php
checks:
  php:
    code_rating: true
    duplication: true
filter:
  excluded_paths:
    - vendor/*
tools:
    php_sim: false
    php_cpd: false
    php_pdepend: true
    php_analyzer: true
    php_changetracking: true
filter:
    excluded_paths:
        - tests/*
        - vendor/*