build:
  environment:
        php:
            version: 7.0.20
  tests:
    override:
      - command: 'vendor/bin/codecept --coverage --coverage-xml'
        coverage:
          file: 'coverage.xml'
          format: 'clover'
checks:
  php:
    code_rating: true
    duplication: true
tools:
    php_analyzer: true
filter:
  excluded_paths:
    - vendor/*
before_commands:
  - "composer global require fxp/composer-asset-plugin:^1.3.1"
  - "composer install --prefer-source"